### ISSUE TITLE
My Learning Materials Not Showing all eligible LMs

### ISSUE THREAD

**Issue by stopfstedt** [ilios/common#1203]
Here is the screen shot from the same data from the Materials area of the Dashboard. There are six LM's displayed here instead of the seven that should be and that were displayed in the ticket above.

![image](https://user-images.githubusercontent.com/7493331/35407832-f388ad38-01c1-11e8-9123-a9382d283c70.png)

The LM that is missing is `End Only Future`. Somehow the LM that only has an End Date that happens to be in the future is not being displayed. It should be available with a message indicating the End Date (per #1201).

_Originally posted by @dartajax in https://github.com/ilios/common/issues/1201#issuecomment-360572508_

**Comment by stopfstedt** [comment]
I don't think that's necessarily true. A learning material's timed release information has no impact on whether the LM is listed here or not. 

What matters is that the LM is attached to an published session or published course that has offerings/ILMs happening in the next sixty days, and that I'm participating in those offerings/ILMs.

Please re-verify. Thanks!

**Comment by ShortonIT** [comment]
Need more details.  Unable to reproduce issue. Interns Nanci/Michael/Stacey @stopfstedt

**Comment by ShortonIT** [comment]
Need more details.  Unable to reproduce issue.  Interns Nanci/Michael/Stacey @stopfstedt 

![Screenshot (305)](https://user-images.githubusercontent.com/103003096/164282413-36918327-1d5c-45d3-935b-cf7e508b2a21.png)

**Comment by dartajax** [comment]
I will re-test this. Initially I was claiming that a learning material that was assigned an "end date" (after which it would no longer be available) in the future and no specific start date was not showing up when it should have. I need to re-test this and think more about the timing of the offering and keep in mind the learning material's start and end dates.

**Comment by dartajax** [comment]
So I have re-tested this. It is no longer an issue - if a learning material has start and end dates both in the past, it shows up but the link is not active. And this is fine with me. This "Materials" area has been greatly revamped and is in a better state than before. This bug has been squashed.
