### ISSUE TITLE
Improve Tooltips On Learner Groups

### ISSUE THREAD

**Issue by dartajax** [ilios/common#1355]
Currently, if you are viewing a learner group that is a sub-group of a parent group, the name of the parent group gets displayed in the tooltip. This is fine and all but lacks context.

If a learner group is the parent group (at the highest level), there is no tool tip. This is also fine; but we can discuss making the tooltips contain the full hierarchical path.

While this may be a bit extreme, here is an example of a tooltip from Vocabulary Terms ...

![image](https://user-images.githubusercontent.com/7493331/80022285-afee2b80-8490-11ea-9a96-958a82b0d5d5.png)

**Comment by dartajax** [comment]
Maybe `Cohort >> Parent LG` and if at top level `Cohort`? or do we need to include School and Program?

**Comment by jrjohnson** [comment]
Should also convert to using `<IliosTooltip>` component eg: https://github.com/ilios/common/blob/master/addon/components/detail-terms-list-item.hbs#L10-L13
