### ISSUE TITLE
If Indiv Learners Are Attached To ILM, We Need To Indicate That Correctly

### ISSUE THREAD

**Issue by dartajax** [ilios/common#1513]
In the screen shot below, two individual learners have been added to the ILM.

![image](https://user-images.githubusercontent.com/7493331/86303213-062dc800-bbc0-11ea-8855-428df36adefd.png)

That fact should be displayed in the screen shot below as well. It even says "(0,1)" where the zero would indicate there are no individual learners attached. At a minimum, that count should be updated. It would be better if the entire display were updated to show the existence of both.

![image](https://user-images.githubusercontent.com/7493331/86303305-4ee58100-bbc0-11ea-95ae-d70d1cb1e612.png)

**Comment by jrjohnson** [comment]
I'm unable to replicate this as of today. @dartajax or @stopfstedt can you check and see if it's working for you as well. I wonder if it was fixed incidentally elsewhere.

**Comment by dartajax** [comment]
It seems to be working better - weird. I just reported this a cpl weeks ago.
