### ISSUE TITLE
Need To Validate URL's Better In Learning Material Links

### ISSUE THREAD

**Issue by dartajax** [ilios/common#1554]
Currently we don't validate links posted as Learning Materials in the proper and most complete way.

![image](https://user-images.githubusercontent.com/7493331/88980614-f534ad00-d278-11ea-9593-ec3f8a081227.png)

Here are the exact links that were saved and posted with the issues.

`Bad URL` = 
![image](https://user-images.githubusercontent.com/7493331/88980726-2ad99600-d279-11ea-86e7-6e362fccaf3f.png)

![image](https://user-images.githubusercontent.com/7493331/88980814-578dad80-d279-11ea-82ce-64abff2bfa63.png)

`Good URL - kind of` = 
![image](https://user-images.githubusercontent.com/7493331/88980879-7db34d80-d279-11ea-9c01-0974c147c124.png)

This may be typical or links that might be pasted in that users would expect to work since in many browsers URL's are displayed without the "https://": or "http://" anyway. When clicked, here is where it tries to go ...

`https://ilios-stage.ucsf.edu/courses/dartajax.bandcamp.com` - it takes the valid URL and tries to append it to `https://ilios-stage.ucsf.edu/courses/` in this case since I tried to access the link from Courses and Sessions. It fails in a similar Zoinks fashion when attempted to be accessed from the Event Detail. See below ...

`https://ilios-stage.ucsf.edu/events/dartajax.bandcamp.com`

`Good URL - really good` = 
![image](https://user-images.githubusercontent.com/7493331/88981146-34afc900-d27a-11ea-83a7-5054c76f24ce.png)

Takes the user to ...
![image](https://user-images.githubusercontent.com/7493331/88981189-4f823d80-d27a-11ea-8deb-4fb9fdf622df.png)

**Comment by stopfstedt** [comment]
resolved via https://github.com/ilios/common/pull/1741
