### ISSUE TITLE
Show learners in offerings grid

### ISSUE THREAD

**Issue by stopfstedt** [ilios/common#1765]
Show selected individual learners as comma separated list with truncation, similar to instuctors and learner groups.
Provide a tooltip/hover-over that shows the names of _all_ selected learners.

Relabel the column that shows the # of selected learners.

![Selection_036](https://user-images.githubusercontent.com/1410427/99299849-ae0b0180-2800-11eb-9f7c-c3ff3912bf4f.png)

refs #802

**Comment by stopfstedt** [comment]
@saschaben and/or @dartajax - any thoughts on how to re-label the column that shows selected learner totals? `Learners Total` is the working label at the moment.

**Comment by jrjohnson** [comment]
How about `(159) Rusty...` or `Rusty... (159)` in a single column?

**Comment by stopfstedt** [comment]
> How about `(159) Rusty...` or `Rusty... (159)` in a single column?

Ah, and here is the first misunderstanding that I was concerned about (but didn't articulate in the ticket's description). Those are _individually_ assigned learners, where-as the total count of learners sums up those and all learners in groups assigned to this offering (after de-duping). Perhaps that column label may need to be expanded as well `Individually assigned learners`. Bah, too long!

**Comment by stopfstedt** [comment]
to roll with @jrjohnson's idea - add totals to to the instructors, learners, and learner-groups columns. then show _all_ assigned learners in the "Learners" column. I like this much better, actually.

![Selection_038](https://user-images.githubusercontent.com/1410427/99301689-2ffc2a00-2803-11eb-933a-5883dc40f8a9.png)

@saschaben @dartajax thoughts?

**Comment by dartajax** [comment]
Would there be a way to hide it if the count = 1? Not a big deal really - just a thought. What does it look like with an offering that has 8 learner groups? Is there a PR?  I'd be glad to give it a test.

**Comment by dartajax** [comment]
That looks nice though.

**Comment by stopfstedt** [comment]
> Would there be a way to hide it if the count = 1? 
i think this would cause more friction as you scan over this table. would like to hear more opinions on this.
