### ISSUE TITLE
Improve Loading Vocabularies

### ISSUE THREAD

**Issue by jrjohnson** [ilios/common#1767]
Because they are so large [loadCourse](https://github.com/ilios/common/blob/master/addon/services/data-loader.js#L54) doesn't currently side load all vocabularies. This makes term management seem slow and weird. We should go ahead and pre-load vocabulries as well, but in a non-blocking way. Maybe add a `loadSchoolVocabularies` to the DataLoader service and call it without awaiting the completion in the course route and then we can call it in other places that we need the full list.

**Comment by nancirose** [comment]
Need additional info. Unable to duplicate issue.

Nanci, Michael, Stacey

**Comment by jrjohnson** [comment]
Fixed in #2886
