### ISSUE TITLE
Edit offering: submit form on press-enter-key in select input elements

### ISSUE THREAD

**Issue by stopfstedt** [ilios/common#1774]
![Selection_049](https://user-images.githubusercontent.com/1410427/99462576-d66e2b00-28e8-11eb-8b59-b88cdfc9e651.png)

when a user presses `Enter` in one of the following fields, the form should be submitted.
these fields are:
- duration hour
- duration minute
- location
- virtual learning link

**Comment by jrjohnson** [comment]
This should only happen when editing an existing offering. When creating a new offering only save should save.
