### ISSUE TITLE
Message of Unlinked Objectives on Publish All Doesn't Appear to be Accurate

### ISSUE THREAD

**Issue by dartajax** [ilios/common#1796]
![image](https://user-images.githubusercontent.com/7493331/99437202-fe4c9700-28c6-11eb-9466-f86db3f9e58c.png)

after clicking on the graph icon in the screen shot reveals this ...

![image](https://user-images.githubusercontent.com/7493331/99437453-55526c00-28c7-11eb-9aae-347c2226d3aa.png)

I'm not seeing any unlinked objective in the visualization. Am I missing something?

**Comment by stopfstedt** [comment]
Minor bug between publish-all component and course objective management - the "unlinked objectives" message is not getting correctly updated as objectives are being worked on while the publish-all dialog is open.

the pie chart only serves to illustrate that all objectives are in fact linked up, there is no problem with the visualization itself.

**Comment by stopfstedt** [comment]
fixed via https://github.com/ilios/common/pull/1727
