### ISSUE TITLE
Copy Session - Slight Layout Improvement Suggestion 

### ISSUE THREAD

**Issue by dartajax** [ilios/common#1804]
![image](https://user-images.githubusercontent.com/7493331/100925163-7bb30280-3496-11eb-8fb1-bb58476a8d71.png)

**Comment by stopfstedt** [comment]
tagging on to that:

![Selection_097](https://user-images.githubusercontent.com/1410427/101419492-f9b34700-38a4-11eb-8118-5ec3d97f89d7.png)
