### ISSUE TITLE
Message Needed When Post-Requisite Session Cannot Be Deleted

### ISSUE THREAD

**Issue by dartajax** [ilios/common#1820]
Users try to delete sessions which have pre-work associated. We do not currently provide any guidance into the reason the session cannot be deleted. There is an icon indicating the existence of pre-work related to that session, but that's it.

![image](https://user-images.githubusercontent.com/7493331/101840679-6cb4fb80-3af9-11eb-8ac7-2b042735fd32.png)

After clicking the delete button as shown by one of the blue arrows in the screen shot below, the following occurs ...

![image](https://user-images.githubusercontent.com/7493331/101840826-ab4ab600-3af9-11eb-92dd-6f73c469cb23.png)

The "Yes" button briefly spins after being clicked and nothing happens. The user is not advised why the session cannot be deleted.

We should have a message with an indication and links to whatever pre-work session(s) are preventing the session from being deleted. The message should advise that the session cannot be deleted until these relationships are removed.

**Comment by stopfstedt** [comment]
after conversing with @dartajax , we agreed that locking down the trashbin is a sufficient enough fix for this problem.
