### ISSUE TITLE
Provide a Method of Navigating to Rolled Over and Ancestor Courses

### ISSUE THREAD

**Issue by dartajax** [ilios/common#1913]
This is something I noticed would be helpful. Basically, if you pull up a Course in 2018-19 but then realize you wanted the 2019-20 course instead. If the 2018-19 course has been rolled over to 2019-20, there should be a way to flip over to the other year's course without having to go back to Courses and Sessions, change the year, do a search or filter again, and then review the other course.

This could also be helpful if a course name has changed slightly and you don't remember what the new title has become. The familial relationship between courses could provide an easy way to navigate between related courses - backwards or forwards. If there is only one course - no predecessors or descendants, the nav buttons would not be activated or not show up at all.

**Comment by mhgh22** [comment]
This probably needs further discussion to understand the issue. The current method of searching courses from different years is with search filter and going through the years from the drop down. -MNS @dartajax

![Untitled](https://user-images.githubusercontent.com/103135575/164326690-1ea87a73-6c62-4ac2-ac53-9bfe4e565255.png)

**Comment by dartajax** [comment]
Further discussion will be forthcoming. I'd be glad to explain what I was trying to get at with this ticket. It's not something that can be done easily so this one may sit in the hopper awhile. Thanks for checking it.

**Comment by stopfstedt** [comment]
turns out we can't do this in a way that's meaningful for end-user under all circumstances. we cannot express "rolled over from" and "rolled over into", if the source course has been rolled over. that's because the root ancestor in the inheritance change will always be stored as the rolled-over course's ancestor, and not the actual source course. the end effect is that a source/target relationship for rolled-over courses cannot be expressed since we don't store this relationship, and it cannot be retrieved after the fact.

**Comment by stopfstedt** [comment]
flagged as `needs team discussion` before this can be closed down. in case someone else sees a solution that i don't.

**Comment by stopfstedt** [comment]
> We could present any course with the common ancestor as a list?

we could, but how is that useful to the end user?

**Comment by jrjohnson** [comment]
Easy navigation to other courses in the same tree, seems to meet @dartajax's needs, but I agree I don't know what the final value is. Plus the list will only grow over time so it's a bit of a UI problem.

**Comment by stopfstedt** [comment]
> Easy navigation to other courses in the same tree, seems to meet @dartajax's needs, but I agree I don't know what the final value is. Plus the list will only grow over time so it's a bit of a UI problem.

i see you point, but i think you're misunderstand the issue - there is no "real" ancestry tree here - only a root and leaves.

to explain the problem by example: if you roll over course B into course C, and course B has been rolled over from course A (or another course that's been rolled over from A - we don't know!), then course C is now linked to course A, and no information about course B can be found in the "ancestry chain".

**Comment by jrjohnson** [comment]
But both B and C have an ancestor of A, so hopefully a query to the API for Course A and all of it's descendants would yield a possibly useful list. I'm not sure *how* useful, but it's something.

**Comment by stopfstedt** [comment]
discussed by the team on 4/26, we're shuttering this.
