### ISSUE TITLE
Session Description Needs to Show Up on Event Detail

### ISSUE THREAD

**Issue by dartajax** [ilios/common#2071]
Here is an example of this ...

Session Description clearly evident.

![image](https://user-images.githubusercontent.com/7493331/115746485-38740600-a349-11eb-91be-625e78583780.png)

Here is the same session shown in Event Detail. Session Description is nowhere to be found.

![image](https://user-images.githubusercontent.com/7493331/115746653-593c5b80-a349-11eb-9e36-dc075617e5a2.png)

**Comment by stopfstedt** [comment]
the cuprit seems to be the `get` helper i this conditional in `single-event.hbs`

```
{{#if (gt (get @event.sessionDescription "length") 0)}}
```

`get @event.sessionDescription "length"` produces the correct length using the dummy app, however if used through the frontend it returns `undefined` on the same input. 

to illustrate this - pulling up the event details in frontend - no session description

![image](https://user-images.githubusercontent.com/1410427/115778102-fc519d00-a36a-11eb-9e6f-463dffaf0777.png)

same event - using common dummy app:

![image](https://user-images.githubusercontent.com/1410427/115778322-5b171680-a36b-11eb-8115-f9204c47913c.png)
