### ISSUE TITLE
school picker on filters not sticky

### ISSUE THREAD

**Issue by saschaben** [ilios/common#2775]
when shifting between "show filters" and "hide filters" on the dashboard calendar, if a school other than the primary school has been selected, when the toggle is shifted the school will revert to the primary school. eg, if I am looking at SOP (as a SOM user) and I open/close the filters, the calendar will flip back from SOP to SOM.

**Comment by mhgh22** [comment]
Able to duplicate issue after clicking on 'All Events" and following the original instruction. Issue is still present(Thanks Stefan). -Michael/Nanci/Stacey
