### ISSUE TITLE
Only Session Pre-Work Links Are Underlined 

### ISSUE THREAD

**Issue by dartajax** [ilios/common#2795]
![image](https://user-images.githubusercontent.com/7493331/163063886-10c4d997-9c4b-4df0-be5c-6c52cfbbf3ed.png)

**Comment by jrjohnson** [comment]
I think for accessibility they all need to be underlined, but this is already fixed so I'll wait for a new site improve scan and we can re-visit.

**Comment by dartajax** [comment]
Do all links need to be underlined then?

**Comment by jrjohnson** [comment]
It depends on the surrounding content. Links that are in their own visual space don't need to be, but links that are embedded in a paragraph do. In this case we may be OK, but it's also possible that the text above and below with trigger a warning for a11y.
