### ISSUE TITLE
translations overwritten in frontend

### ISSUE THREAD

**Issue by stopfstedt** [ilios/common#2804]
the following `general` keys exist in the translation files in both common and frontend, the effect is that frontend overwrites those keys. 

```
fileSizeError
ilios
login
next
noResultsFound
pagedResultsCount
schools
search
selectCourse
```

copy the values from frontend into common if they differ. then, remove all lang keys entries listed above from the frontend.

**Comment by mhgh22** [comment]
Unable to review isssue. -MNS

**Comment by stopfstedt** [comment]
this one's done.
