### ISSUE TITLE
An Offering Of Zero Hours and Zero Minutes Should Not Be Saved

### ISSUE THREAD

**Issue by dartajax** [ilios/common#2840]
II found that it is possible to save an offering with a date and no duration whatsoever. Example below ...

<img width="1196" alt="Screen Shot 2022-05-04 at 10 08 58 AM" src="https://user-images.githubusercontent.com/7493331/166741919-40059de5-cf37-49ad-ba4e-d51010a148f7.png">

Since there is no way this could ever shown up on a calendar, we should require a duration for an offering. Or at least we should talk about requiring a duration for an offering.

**Comment by mhgh22** [comment]
Here is a meeting with 0 time duration showing up on the calendar(appears as a small square):

![Untitled](https://user-images.githubusercontent.com/103135575/167461758-77879db4-231b-4528-ac49-96c6a852855f.png)

-MNS @dartajax
