### ISSUE TITLE
Grid Underflow in Offering Editor

### ISSUE THREAD

**Issue by jrjohnson** [ilios/common#2887]
![image](https://user-images.githubusercontent.com/7493331/172932362-b5fe4219-31db-40ea-a2a7-0dea1da9ebce.png)

_Originally posted by @dartajax in https://github.com/ilios/frontend/issues/6679#issuecomment-1151556297_

**Comment by jrjohnson** [comment]
I think this is a regression from https://github.com/ilios/common/pull/2843 gonna assign to @stopfstedt and @dartajax as I'm lazy and couldn't tell at a glance what the original fix was doing and I don't want to mess it up attempting to fix this issue.

**Comment by stopfstedt** [comment]
this makes a bit more sense when table headers are shown in the screenshot:

![image](https://user-images.githubusercontent.com/1410427/173151920-8c8fc1b6-0829-4302-9065-895e428b7a04.png)

**Comment by stopfstedt** [comment]
there is no easy fix for this, other than going back to rows vs. columns.

screenshot from demo
![image](https://user-images.githubusercontent.com/1410427/173153359-68116d17-ca49-4252-930a-b50ee615b5cb.png)

so do we want unused white space up top or to the left? pick your poison.

**Comment by dartajax** [comment]
This has been fixed - we went with the space to the left being sacrificed rather than the vertical. Looks good to me as it is so gonna close this ticket.
