### ISSUE TITLE
Fit session attributes into less space

### ISSUE THREAD

**Issue by jrjohnson** [ilios/common#2888]
on demo ... all three of these "Session Attributes" fit - keep in mind there may be more than 3 of these - schools can customize them - as SOP has.

<img width="1285" alt="old" src="https://user-images.githubusercontent.com/7493331/172936020-d24bf8a4-a275-4eec-ba93-e18553c0ed3e.png">

on PR ... Same screen size - the image has a diff width because I selected the range by hand. Only two fit here. 

<img width="1229" alt="new" src="https://user-images.githubusercontent.com/7493331/172936064-a375ec3d-c24e-4b64-9b8f-4af062bb456a.png">

_Originally posted by @dartajax in https://github.com/ilios/frontend/issues/6679#issuecomment-1151576192_

**Comment by stopfstedt** [comment]
the latest frontend snaps from two to three toggles in a row at `1441px` screen width, whereas common does that at `1459px` 
demo still has an old frontend, which snaps at `1430px`. 

all observations made using latest FF on Linux.

**Comment by dartajax** [comment]
New layout ticket will be coming soon. This can go away.
