### ISSUE TITLE
rm explicit dependency on ember-concurrency

### ISSUE THREAD

**Issue by stopfstedt** [ilios/common#502]
we're getting ember-concurrency already from ember-simple-charts.
yank the import from `package.json` here.

**Comment by jrjohnson** [comment]
Not sure about this. It couples us tightly with simple charts which happens to be our add-on, but it's still an add-on.

**Comment by stopfstedt** [comment]
fair. i was getting grief from the dependency checker further upstream (lti-dashboard), hence the request. will whitelist things up there.

**Comment by jrjohnson** [comment]
I just removed all the white listing in frontend and it was clear. Maybe check package.json on frontend for differences?

**Comment by stopfstedt** [comment]
regenerating the lock file in lti-dashboard flushed this dependency mismatch out.
