### ISSUE TITLE
Instructional Notes Font Size Not Consistent

### ISSUE THREAD

**Issue by dartajax** [ilios/common#554]
![image](https://user-images.githubusercontent.com/7493331/53978860-12377180-40c1-11e9-81a3-e40d25fdab8d.png)

**Comment by stopfstedt** [comment]
@dartajax how'd you make that happen? please send me the markup for the larger note (copy/paste from your browser's source inspector). thanks!

**Comment by dartajax** [comment]
Instructional Note font size is pretty consistent. Can't reproduce - gonna close. 

![image](https://user-images.githubusercontent.com/7493331/56620866-3acaea80-65df-11e9-9322-6130d22d8dcc.png)
