### ISSUE TITLE
We Need At Least A Space Here nbsp& or Whatever - Session Description

### ISSUE THREAD

**Issue by dartajax** [ilios/common#561]
![image](https://user-images.githubusercontent.com/7493331/54047432-e2a16b80-418b-11e9-8cb2-161f95fb8aec.png)

![image](https://user-images.githubusercontent.com/7493331/54047468-f5b43b80-418b-11e9-8037-cd7526e1704f.png)

**Comment by stopfstedt** [comment]
this is by design, once you go over a certain length, you get a "clean", abbreviated version of the text, devoid of all markup, line-breaks etc.
