### ISSUE TITLE
user search: show preferred email ... somewhere?

### ISSUE THREAD

**Issue by stopfstedt** [ilios/common#564]
example:
![Selection_351](https://user-images.githubusercontent.com/1410427/54305740-211c9900-4585-11e9-859c-d8567014d225.png)

another example, this time from the course leadership user search:

![Selection_352](https://user-images.githubusercontent.com/1410427/54310160-f7686f80-458e-11e9-89f8-1c89b050f9ab.png)

options: 
- show both default and preferred email if pref email is available
- show only preferred email if available
- leave as-is, and only show default email

**Comment by jrjohnson** [comment]
I vote for *official* email in the search box since the point it to ID the user when there are name conflicts. Then add preferred email as you have it in the user view.  Also - probably a frontend issue, I don't think admin components are in common.

**Comment by stopfstedt** [comment]
yes, but the user search is in common. i used the admin screenshot as an example since i'm working on this right now, sorry for the confusion.

**Comment by jrjohnson** [comment]
I didn't know search was here. Ok. Sorry. SO MANY PLACES!!

**Comment by stopfstedt** [comment]
per team conversation, we leave this _as-is_ and only show the default email in all cases.
