### ISSUE TITLE
Student View of All Events Should Never Contain Other Schools In the Drop-Down

### ISSUE THREAD

**Issue by dartajax** [ilios/common#611]
What I mean by this is the following ...

I am logged in as a student (SOM Class of 2021 BRIDGES). This student ...

![image](https://user-images.githubusercontent.com/7493331/46507905-c9b51880-c7ef-11e8-86a7-59b1ce308d3e.png)

I tried what I am reporting in an incognito window as well to verify it wasn't caching issues or something.

Here is what I see after turning on All Events ...

![image](https://user-images.githubusercontent.com/7493331/46508017-5bbd2100-c7f0-11e8-8f17-8dbab6d76f50.png)

Those other schools should not be available -School of Medicine should be displayed only with no drop-down whatsoever.

**Comment by jrjohnson** [comment]
Need to decide if we want to restrict this for students or not. If we do want to restrict we'll need to figure out how to tell what schools a users is allowed to access.

**Comment by dartajax** [comment]
We may close this ticket in lieu of a better one that limits the drop-down to contain all schools for which the user has permission.

**Comment by mhgh22** [comment]
Issue is still present when logged in as student. -MNS @dartajax 

![illios](https://user-images.githubusercontent.com/103135575/164278216-e86d0600-5c28-4c87-a9d5-6cb170e61bf9.png)

**Comment by stopfstedt** [comment]
discussed with team on 4/28/22. we decided that it's fine as-is/no need to change this.
